// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
type CloudflareBindings = {
  DB: D1Database;

  JWT_SECRET_KEY: string;
  JWT_EXPIRES_IN: number;
  JWT_REFRESH_EXPIRES_IN: number;
};
